const cakes = [
  'best1.jpg',
  '2_etaj.jpg',
  'rose_princess.jpg',

  'childrens.jpg',
  'damian.jpg',
  'dark_2_cake.jpg',
  'maxim_kristini_1_year.jpg',
  'minion_cake.jpg',
  'qiwy.jpg',
  'roses.jpg',

  'best_2.jpg',
  'bicicle.jpg',
  'cyan.jpg',
  'gucci.jpg',
  'hohoho.jpg',
  'kotick.jpg',
  'kreshenie.jpg',
  'macarons.jpg',
  'new_year.jpg',
  'piano.jpg',
  'princess32.jpg',
  'childrens2.jpg',
  'princess_makarons.jpg',
  'rabbit.jpg',
  'robert.jpg',
  'rochie_3.jpg',
  'rubashka.jpg',
  'sane_6_let.jpg',
  'pohlava.jpg',
  'spanch_bob_cake.jpg',
  'strawberry4.jpg',
  // 'tachkis.jpg',
  'tracktor_cake.jpg',
  '18+_cake.jpg',
  '18+_nevesta.jpg',
  '5section.jpg',
  'beautifull_face_cake.jpg',
]

export default cakes
